/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile


plugins {
  // Apply the Kotlin JVM plugin to add support for Kotlin.
  kotlin("jvm") version "1.3.61"

  // Apply the application plugin to add support for building a CLI application.
  application
}

java {
  sourceCompatibility = JavaVersion.VERSION_1_8
  targetCompatibility = JavaVersion.VERSION_1_8
}

repositories {
  // Use jcenter for resolving dependencies.
  // You can declare any Maven/Ivy/file repository here.
  jcenter()
}

dependencies {
  implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
  // CDK
  implementation("software.amazon.awscdk:core:1.15.0.DEVPREVIEW")
  implementation("software.amazon.awscdk:iam:1.15.0.DEVPREVIEW")
  implementation("software.amazon.awscdk:ecs:1.15.0.DEVPREVIEW")
  implementation("software.amazon.awscdk:ecs-patterns:1.15.0.DEVPREVIEW")
  implementation("software.amazon.awscdk:ecr:1.15.0.DEVPREVIEW")
  implementation("software.amazon.awscdk:ec2:1.15.0.DEVPREVIEW")
  implementation("software.amazon.awscdk:rds:1.15.0.DEVPREVIEW")
  implementation("software.amazon.awscdk:ssm:1.15.0.DEVPREVIEW")
  // Testing
  testImplementation("org.jetbrains.kotlin:kotlin-test")
  testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

application {
  // Define the main class for the application.
  mainClassName = "io.code.morning.AppKt"
}

tasks {
  val buildZip by registering(Zip::class) {
    from(compileKotlin)
    from(processResources)
    into("lib") {
      from(configurations.compileClasspath)
    }
  }
  named("build") {
    dependsOn(buildZip)
  }
}

tasks.withType<KotlinCompile> {
  kotlinOptions {
    freeCompilerArgs = listOf("-Xjsr305=strict")
    jvmTarget = "1.8"
  }
}
